on:
  push:
    branches:
      - main
  pull_request:

name: Continuous Integration

jobs:

  linux_dbus:
    name: linux (dbus)
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
          - stable
          - 1.73.0
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.rust }}
          override: true
      - run: rustup component add clippy
      - run: sudo apt-get install -y libdbus-1-dev

      - name: check
        uses: actions-rs/cargo@v1
        with:
          command: check
          args: --no-default-features --features d

      #- name: test
      #  uses: actions-rs/cargo@v1
      #  with:
      #    command: test
      #    args: --lib --no-default-features --features d

      #- name: doc_test
      #  uses: actions-rs/cargo@v1
      #  with:
      #    command: test
      #    args: --doc --no-default-features --features d

      #- name: test_features_images
      #  uses: actions-rs/cargo@v1
      #  with:
      #    command: test
      #    args: --lib --no-default-features --features d,images

      #- name: doc_test_features_images
      #  uses: actions-rs/cargo@v1
      #  with:
      #    command: test
      #    args: --doc --no-default-features --features d,images

      - name: clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --no-default-features --features d -- -D warnings

  linux_zbus:
    name: linux (zbus)
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
          - stable
          - 1.60.0
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.rust }}
          override: true
      - run: rustup component add clippy
      - run: sudo apt-get install -y libdbus-1-dev

      - name: check
        uses: actions-rs/cargo@v1
        with:
          command: check
          args: --no-default-features --features z

      #- name: test (zbus)
      #  uses: actions-rs/cargo@v1
      #  with:
      #    command: test
      #    args: --lib --no-default-features --features z

      #- name: doc_test (zbus)
      #  uses: actions-rs/cargo@v1
      #  with:
      #    command: test
      #    args: --doc --no-default-features --features z

      #- name: test_features_images (zbus)
      #  uses: actions-rs/cargo@v1
      #  with:
      #    command: test
      #    args: --lib --no-default-features --features "z images"

      #- name: doctest_features_images (zbus)
      #  uses: actions-rs/cargo@v1
      #  with:
      #    command: test
      #    args: --doc --no-default-features --features "z images"

      - name: clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --no-default-features --features "z images" -- -D warnings

  windows:
    name: windows
    runs-on: windows-latest
    strategy:
      matrix:
        rust:
          - stable
          - 1.60.0
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.rust }}
          override: true
      - run: rustup component add clippy
      - name: check
        uses: actions-rs/cargo@v1
        with:
          command: check
      #- name: test
      #  uses: actions-rs/cargo@v1
      #  with:
      #    command: test
      #    args: --no-run
      - name: clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: -- -D warnings

  macos:
    name: macos
    runs-on: macos-latest
    strategy:
      matrix:
        rust:
          - stable
          - 1.60.0
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.rust }}
          override: true
      - run: rustup component add clippy
      - name: check
        uses: actions-rs/cargo@v1
        with:
          command: check
      #- name: test
      #  uses: actions-rs/cargo@v1
      #  with:
      #    command: test
      #    args: --no-run
      - name: clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: -- -D warnings
